version: '3.6'

services:

  webapp:
    build: ./webapp
    container_name: web-app-container
    depends_on:
      - postgres-db
    ports: 
      - "${PORT}:${PORT}"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./webapp:/usr/src/app
    networks:
     - rtls-uwb-network
  
  postgres-db:
    build: 
      context: ./postgres
      args: 
        - pg_version=${POSTGRES_VERSION}
    container_name: postgres-db-container
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    networks:
     - rtls-uwb-network

networks:
  rtls-uwb-network:
    driver: bridge