DROP TABLE IF EXISTS "ADMINISTRADORES";
CREATE TABLE "ADMINISTRADORES"
(
    "ID" SERIAL PRIMARY KEY,
    "NOME" VARCHAR(100)
);

DROP TABLE IF EXISTS "CLIENTES" CASCADE;
CREATE TABLE "CLIENTES"
(
    "ID" SERIAL PRIMARY KEY,
    "NOME" VARCHAR(100),
    "IDADE" INTEGER,
    "ENDERECO" VARCHAR(100),
    "NUM_CONTA" SERIAL
);

DROP TABLE IF EXISTS "CONTAS" CASCADE;
CREATE TABLE "CONTAS"
(
    "ID" SERIAL PRIMARY KEY,
    "CLIENTE_ID" INTEGER REFERENCES "CLIENTES"("ID") ON DELETE CASCADE,
    "SALDO" FLOAT
);

DROP TABLE IF EXISTS "TRANSACOES";
CREATE TABLE "TRANSACOES"
(
    "ID" SERIAL PRIMARY KEY,
    "CONTA_ID" INTEGER REFERENCES "CONTAS"("ID") ON DELETE CASCADE,
    "TIMESTAMP" NUMERIC,
    "NATUREZA" VARCHAR(100),
    "VALOR" FLOAT
);